In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### 필요한 모듈 import, 파일 읽어오기

In [2]:
import numpy as np
import pandas as pd

with open('/content/drive/MyDrive/Colab Notebooks/project/injury45.txt','r') as f:    #injury45.txt 읽어오기.
    injury45 = f.readlines()
    """readlines()로 파일을 읽으면 하나의 리스트에 한줄씩 저장된다."""
    print(len(injury45))    # readlines() 메소드를 사용하면 줄 바꿈을 기준으로 매 줄을 각각 리스트의 요소로 하는 리스트를 반환하기때문에 결국 데이터 수를 알 수 있다.

248


### 읽어온 파일을 데이터프레임에 넣기위해 빈 데이터프레임 만들기

In [3]:
  # DataFrame column 만들기 
  """데이터프레임을 만드는 이유:
  1.데이터를 확인한 뒤 필요한 데이터만 추출, 2.한번에 리스트나 numpy.array로 바꾸기 쉽기 때문이다."""
col = ['user', 'reception_time'] # col list에 데이터프레임의 column 이름을 저장함. user와 reception_time은 단일 이름이므로 미리 넣어둠.
distance_col_list = []  # 이 list에 distance_radar_1,2,3,4 를 넣기 위해 빈 리스트 생성
speed_col_list = []     
    
for i in range(4):    
    distance = 'distance_radar_{}'.format(i+1)
    speed = 'speed_radar_{}'.format(i+1)

  
        
    distance_col_list.append(distance)  #distance_col_list에 for문에 distance_radar_1,2,3,4를 삽입.
    speed_col_list.append(speed)

    
col.extend(distance_col_list)    # col list에 distance_col_list, speed_col_list를 병합.
col.extend(speed_col_list)

    #데이터 프레임 생성
df = pd.DataFrame(index =range(len(injury45)),columns=col)  #data의 수만큼 인덱스를 만들고, columns에는 col을 넣는다.


### 만들어 놓은 빈 데이터프레임에 데이터 넣기

In [4]:
injury45   # injury45.txt 파일


['1,55659769,3.6225,3.4632,0.0,1.6845,1.0871,0.016243,0.0,0.27202\n',
 '1,55659808,3.6398,3.4592,0.0,1.6828,0.96222,0.0030488,0.0,0.24547\n',
 '1,55659825,3.6625,3.4562,1.6575,1.6811,0.8993,-0.0054101,0.0,0.22272\n',
 '1,55659850,3.674,3.4572,1.652,1.6795,0.87509,-0.0025611,-0.10962,0.203\n',
 '1,55659889,3.6855,3.4607,1.6597,1.6829,0.85434,0.0060928,0.032479,0.20097\n',
 '1,55659903,3.701,3.459,1.6586,1.6862,0.79779,-0.012178,0.01218,0.19917\n',
 '1,55659932,3.7226,3.4513,1.6628,1.688,0.81391,-0.056027,0.048718,0.18334\n',
 '1,55659968,3.7332,3.4436,1.6673,1.6871,0.75773,-0.095004,0.057854,0.14007\n',
 '1,55659988,3.7398,3.4336,1.6688,1.6692,0.73689,-0.11571,0.059546,0.056024\n',
 '1,55660025,3.7413,3.4436,1.6702,1.6565,0.68817,-0.093786,0.060899,0.0048682\n',
 '1,55660047,3.7307,3.4512,1.6656,1.6612,0.60535,-0.062118,0.032479,-0.015838\n',
 '1,55660086,3.7175,3.4437,1.657,1.6462,0.50304,-0.076734,-0.0018753,-0.05116\n',
 '1,55660104,3.7015,3.4413,1.6433,1.6486,0.36419,-0.079169,-0.04

In [5]:
for i in range(248):
    df.iloc[i] = injury45[i].split(',')     # injury45의 요소를 ','를 기준으로 나누면(split하면)  
                                            # injury45[0] = '1,55659769,3.6225,3.4632,0.0,1.6845,1.0871,0.016243,0.0,0.27202\n'가
                                            # ['1','55659769','3.6225', '3.4632' ... ] 리스트가 된다. 
                                            # 이 리스트를 df(데이터프레임)의 행에 순서대로 값을 넣어준다. 


In [6]:
df    # 빈 데이터프레임에 값이 다 들어간 것을 확인.

user reception_time  ... speed_radar_3  speed_radar_4
0      1       55659769  ...           0.0      0.27202\n
1      1       55659808  ...           0.0      0.24547\n
2      1       55659825  ...           0.0      0.22272\n
3      1       55659850  ...      -0.10962        0.203\n
4      1       55659889  ...      0.032479      0.20097\n
..   ...            ...  ...           ...            ...
243    1       55666652  ...      -0.15225       0.0609\n
244    1       55666708  ...     -0.054811      0.14007\n
245    1       55666715  ...     -0.042631      0.14007\n
246    1       55666735  ...      -0.02436     0.036539\n
247    1       55666769  ...      0.048721  -5.9539e-07\n

[248 rows x 10 columns]

### 데이터프레임에서 필요한 데이터(필요한 column)만 추출 및 데이터타입 변경, array로 변환.

In [7]:
distance_df = df[['distance_radar_1','distance_radar_2','distance_radar_3','distance_radar_4']]  # 면적을 구해야하기 때문에 df의 거리 관련 열만 뽑아낸다. distance_df에 저장.
distance_df = distance_df.astype('float') # distance_df 의 데이터가 object(문자열)이므로 float으로 변환. 문자열이면 계산을 할 수 없기 때문. 

In [8]:
distance_df    # distance_df에 거리 정보만 담은 것을 확인.

distance_radar_1  distance_radar_2  distance_radar_3  distance_radar_4
0              3.6225            3.4632            0.0000            1.6845
1              3.6398            3.4592            0.0000            1.6828
2              3.6625            3.4562            1.6575            1.6811
3              3.6740            3.4572            1.6520            1.6795
4              3.6855            3.4607            1.6597            1.6829
..                ...               ...               ...               ...
243            1.9363            1.4596            3.2213            3.6522
244            1.9466            1.4622            3.2540            3.6700
245            1.9492            1.4573            3.2541            3.6676
246            1.9642            1.4858            3.2567            3.6495
247            1.9716            1.4885            3.2793            3.6370

[248 rows x 4 columns]

In [9]:
distance_df.dtypes   # 각 column의 데이터는 float임을 확인.

distance_radar_1    float64
distance_radar_2    float64
distance_radar_3    float64
distance_radar_4    float64
dtype: object

In [10]:

distance_df.describe()   #describe() 메소드는 각종 통계량을 요약해서 출력해준다. DataFrame에 사용할 때에는 열에 대해 요약을 수행함.

distance_radar_1  distance_radar_2  distance_radar_3  distance_radar_4
count        248.000000        248.000000        248.000000        248.000000
mean           2.486625          2.039017          2.736038          3.026956
std            0.621482          0.716248          0.725741          0.729530
min            1.917700          1.327400          0.000000          1.638400
25%            1.985250          1.466175          2.107200          2.417350
50%            2.165000          1.657950          3.104550          3.315750
75%            3.000700          2.583200          3.339175          3.639925
max            3.741300          3.463200          3.559800          3.827800

In [11]:
distance_numpy_array = distance_df.to_numpy()  # distance_df에 있는 데이터로 복잡한 계산을 해야하므로 numpy array로 변환해준다.

print(type(distance_numpy_array))              # numpy array 정보 확인
print(distance_numpy_array[0].dtype)
print(distance_numpy_array[0])

<class 'numpy.ndarray'>
float64
[3.6225 3.4632 0.     1.6845]


In [12]:
distance_numpy_array      # numpy array로 변환된 것을 확인 

array([[3.6225, 3.4632, 0.    , 1.6845],
       [3.6398, 3.4592, 0.    , 1.6828],
       [3.6625, 3.4562, 1.6575, 1.6811],
       [3.674 , 3.4572, 1.652 , 1.6795],
       [3.6855, 3.4607, 1.6597, 1.6829],
       [3.701 , 3.459 , 1.6586, 1.6862],
       [3.7226, 3.4513, 1.6628, 1.688 ],
       [3.7332, 3.4436, 1.6673, 1.6871],
       [3.7398, 3.4336, 1.6688, 1.6692],
       [3.7413, 3.4436, 1.6702, 1.6565],
       [3.7307, 3.4512, 1.6656, 1.6612],
       [3.7175, 3.4437, 1.657 , 1.6462],
       [3.7015, 3.4413, 1.6433, 1.6486],
       [3.6629, 3.4339, 1.6373, 1.6436],
       [3.6576, 3.4265, 1.6338, 1.6458],
       [3.6548, 3.4216, 1.6194, 1.6384],
       [3.6518, 3.4192, 1.621 , 1.6434],
       [3.644 , 3.4143, 1.6175, 1.6484],
       [3.6412, 3.4092, 1.6041, 1.6584],
       [3.6385, 3.3992, 1.6015, 1.6583],
       [3.6331, 3.4043, 1.5815, 1.6732],
       [3.6275, 3.3893, 1.5689, 1.7032],
       [3.6099, 3.3596, 1.5613, 1.7182],
       [3.5971, 3.3499, 1.5488, 1.7539],
       [3.6   , 

### 객체 면적을 구하기 위해 필요한 데이터 가공

In [13]:
room_size = 3.15 * 4.95   # 가로 : 3.15, 세로 : 4.95 인 방 면적을 구한다. 
print(room_size)          # 방의 면적: 15.5925

15.5925


In [14]:
# 각 레이더 길이 데이터를 반지름으로 하는 1/4*(원의 넓이)를 구한다. 원의 넓이: pi * (r **2)
circle_size_4 = (1/4 * (np.pi * np.square(distance_numpy_array)))  # 1/4 : 원의 면적의 1/4만 필요하기 때문, distance_numpy_array:각 레이더의 반지름, 
circle_size_4                                                      # np.pi : 3.141592... , np.square()는 제곱(**2) 메소드


array([[10.30639231,  9.41987255,  0.        ,  2.2285989 ],
       [10.405068  ,  9.39812519,  0.        ,  2.22410296],
       [10.53525733,  9.38183116,  2.15772928,  2.21961156],
       [10.60152118,  9.38726094,  2.14343327,  2.2153885 ],
       [10.66799276,  9.40627751,  2.16346099,  2.2243673 ],
       [10.75791359,  9.39703848,  2.16059419,  2.23309938],
       [10.883852  ,  9.35524799,  2.1715504 ,  2.23786954],
       [10.94592317,  9.31355063,  2.18331994,  2.23548383],
       [10.98466043,  9.25953722,  2.18725019,  2.18829886],
       [10.99347389,  9.31355063,  2.19092162,  2.15512647],
       [10.93126784,  9.35470587,  2.17886993,  2.16737334],
       [10.85405045,  9.31409155,  2.15642768,  2.12840895],
       [10.76082054,  9.30111363,  2.1209166 ,  2.1346195 ],
       [10.53755868,  9.26115534,  2.10545714,  2.12169106],
       [10.50708629,  9.22128306,  2.09646523,  2.12737474],
       [10.49100548,  9.19492849,  2.05967241,  2.10828714],
       [10.47378971,  9.

In [15]:
print(len(circle_size_4))

248


In [16]:
circle_size_sum = circle_size_4.sum(axis=1) # 가로 방향으로 4개씩 더해준다 -> axis = 1

In [17]:
circle_size_sum 

array([21.95486376, 22.02729615, 24.29442934, 24.34760389, 24.46209856,
       24.54864564, 24.64851993, 24.67827757, 24.6197467 , 24.65307261,
       24.63221698, 24.45297863, 24.31747028, 24.02586222, 23.95220932,
       23.85389352, 23.84074275, 23.77377409, 23.72248771, 23.64677107,
       23.63217096, 23.56858009, 23.3327336 , 23.27598541, 23.13536838,
       23.00315512, 22.82736362, 22.81215808, 22.66842432, 22.70023363,
       22.63612643, 22.40829588, 22.401786  , 22.43208244, 22.06731814,
       22.13260588, 21.98298538, 21.91134431, 21.85837241, 21.73204515,
       21.70646497, 21.66846033, 21.52994366, 21.57328769, 21.51477851,
       21.38050293, 21.18743693, 21.1138832 , 21.03995899, 20.94299381,
       20.89837392, 20.82920871, 20.81708704, 20.86999925, 20.61418566,
       20.60890594, 20.64904515, 20.65945627, 20.35047802, 20.38596612,
       20.17558443, 20.44726287, 20.37073075, 20.49543023, 20.45420188,
       20.31612675, 20.11631018, 20.1319141 , 20.01826425, 20.14

In [18]:
len(circle_size_sum)

248

In [19]:
distance_radar2 = distance_numpy_array[:,1]      

In [20]:
distance_radar3 = distance_numpy_array[:,2]

In [21]:
distance_radar_plus_2_3 = distance_radar2 + distance_radar3

In [22]:
max(distance_radar_plus_2_3)

5.1204

In [24]:
distance_radar1 = distance_numpy_array[:,0]

In [25]:
distance_radar4 = distance_numpy_array[:,3]

In [26]:
distance_radar_plus_1_4 = distance_radar1 + distance_radar4

In [27]:
distance_radar_plus_1_4

array([5.307 , 5.3226, 5.3436, 5.3535, 5.3684, 5.3872, 5.4106, 5.4203,
       5.409 , 5.3978, 5.3919, 5.3637, 5.3501, 5.3065, 5.3034, 5.2932,
       5.2952, 5.2924, 5.2996, 5.2968, 5.3063, 5.3307, 5.3281, 5.351 ,
       5.3737, 5.3664, 5.3727, 5.373 , 5.3531, 5.3684, 5.3832, 5.3858,
       5.4131, 5.413 , 5.4073, 5.4298, 5.4146, 5.4172, 5.4317, 5.4239,
       5.4388, 5.4361, 5.4188, 5.4418, 5.4589, 5.4389, 5.4134, 5.3982,
       5.3957, 5.3857, 5.3899, 5.3603, 5.3675, 5.3923, 5.365 , 5.3728,
       5.3852, 5.3869, 5.347 , 5.3645, 5.3558, 5.4179, 5.4181, 5.4336,
       5.4391, 5.4465, 5.4239, 5.4457, 5.4209, 5.441 , 5.4264, 5.4046,
       5.4118, 5.4191, 5.4159, 5.4052, 5.3829, 5.4052, 5.3995, 5.4021,
       5.4071, 5.3852, 5.3924, 5.3896, 5.3726, 5.3876, 5.4399, 5.445 ,
       5.4505, 5.4656, 5.4679, 5.4635, 5.4852, 5.4678, 5.4605, 5.4608,
       5.4728, 5.4657, 5.4608, 5.4508, 5.438 , 5.4272, 5.3699, 5.3816,
       5.3691, 5.3989, 5.4115, 5.4118, 5.4091, 5.4166, 5.4341, 5.4415,
      

In [28]:
max(distance_radar_plus_1_4)

5.822

In [29]:
np.where(distance_radar_plus_1_4 == 5.822)

(array([178]),)

### 두 원의 교차면적 구하기


#### 우리 조건에서 두 원의 중심 사이의 거리 d는 세로는 4.95, 가로는 3.15로 고정이다. 즉 (R1,R2), (R3,R4)의 반지름의 합이 4.95를 초과하면 두 원이 겹치는 부분이 생기게 된다. 마찬가지로 (R1,R3),(R2,R4) 반지름의 합이 3.15를 초과하면 두 원이 겹치는 부분이 생긴다. 

In [30]:
#예시 
# a = distance_numpy_array[0][0]
# b = distance_numpy_array[0][1]
# d = distance_numpy_array[0][0] + dstance_numpy_array[0][1]
# print(a,b,d)
a=distance_numpy_array[0][0]
b = distance_numpy_array[0][1]
d = 4.95
print(a,b,d)

3.6225 3.4632 4.95


In [31]:
A = ((d**2) + ((a**2) - (b**2))) / (2*a*d)     

B = ((d**2) - ((a**2) - (b**2))) / (2*b*d)     
print(A)
print(B)

0.7147040316205534
0.6817349981099982


In [32]:
2 * np.arccos(A)
2 * np.arccos(B)

1.6413295800680678

In [33]:
 2 * np.arccos(A) - np.sin((2 * np.arccos(A))) 
 2 * np.arccos(B) - np.sin((2 * np.arccos(B)))

0.643816018896624

In [34]:
(a**2)*(2 * np.arccos(A) - np.sin((2 * np.arccos(A))))
(b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B))))

7.721771106421305

In [35]:
np.sin((2 * np.arccos(A)))

0.9997666127167283

In [36]:
(a**2)*(2 * np.arccos(A)) - np.sin((2*np.arccos(A))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B))))

27.05127229065349

In [37]:
S = (1/2)*((a**2)*(2 * np.arccos(A) - np.sin((2*np.arccos(A)))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B)))))

In [38]:
S

7.465797639726812

In [39]:
S*(1/2)

3.732898819863406

In [40]:
def intersection_area(a,b,d):
    return (1/2)*(1/2)*((a**2)*(2 * np.arccos(A) - np.sin((2*np.arccos(A)))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B)))))

In [41]:
intersection_area(3.6225,3.4632,4.95)

3.732898819863406

In [ ]:
#객체면적 = 방 면적 - 부채꼴의 넓이의 합 + 교차면적 + 초과면적

In [43]:
# 객체 면적을 구하기 위한 여러 식 만들기 
import math

# 1. 방 면적
room_size = 3.15 * 4.95 

# 2.각 레이더 길이 데이터를 반지름으로 하는 부채꼴의 넓이,  원의 넓이: pi * (r **2)  # array로 return
def circular_sector_area(index):
    
    return (1/4 * (np.pi * np.square(distance_numpy_array[index])))

# 3. 두 원의 교차 면적 구하기  
def intersection_area(a,b,d):  
    
    A = ((d**2) + ((a**2) - (b**2))) / (2*a*d)     
    B = ((d**2) - ((a**2) - (b**2))) / (2*b*d)
    # if d = 3.15:
    if a+b < d:
        return 0
    elif (a == 0 or b == 0) and a + b > d:
        return 0
    elif (0 < a < d and 0 < b < d) and a + b > d:
        return (1/2)*(1/2)*((a**2)*(2 * np.arccos(A) - np.sin((2*np.arccos(A)))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B)))))
    elif 0 < a < d and b > d:
        if b * np.sin(np.arccos( d / b )) >= a:
            return (1/4) * np.pi * np.square(a)
        else:
            (1/2) *( (1/2)*((a**2)*(2 * np.arccos(A) - np.sin((2*np.arccos(A)))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B))))) - excess_area(b,d) )
    elif 0 < b < d and a > d:
        if a * np.sin(np.arccos( d / a )) >= b:
            return (1/4) * np.pi * np.square(b)
        else:
            return (1/2) *( (1/2)*((a**2)*(2 * np.arccos(A) - np.sin((2*np.arccos(A)))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B))))) - excess_area(a,d) )
        
    

   
   
    # if a + b <= d:    # 두 원이 교차하지 않거나 접할 경우, 교차면적 자체가 없으므로 0을 출력
    #     return 0
    # else:
    #     if a <= (b * np.sin(np.arccos( d / b ))):
    #         if a > d:
    #             return (1/4) * np.pi * np.square(a) - excess_area(a,d)
    #         else:
    #             return  (1/4) * np.pi * np.square(a)   # 하나의 부채꼴이 다른 부채꼴을 포함하는 경우의 교차 면적
    #     elif b <= (a * np.sin(np.arccos( d / a ))):
    #         if b > d:
    #             return (1/4) * np.pi * np.square(b) - excess_area(a,d)
    #         else:
    #             return (1/4) * np.pi * np.square(b)
    #     else:
    #         return (1/2)*((a**2)*(2 * np.arccos(A) - np.sin((2*np.arccos(A)))) + (b**2)*(2 * np.arccos(B) - np.sin((2 * np.arccos(B)))))

# 4. 한 원의 반지름이 방의 길이를 초과하는 경우 레이더의 부채꼴이 방을 초과하는 부분이 발생한다. 그 부분을 구하는 식  
# def excess_area(r,d):
#     # np.cos(theta) = d / r
#     room_diagonal = np.sqrt(np.square(3.15)+np.square(4.95))
#     theta = np.arccos( d / r )
#     S = (1/2) * np.square(r) * theta  # 부채꼴의 넓이
#     T = (1/2) * d * r * np.sin(theta)  # 삼각형의 넓이
   
#     if r > d :
#         return (1/2) * (S - T)   # S-T 넓이의 반만 필요하기때문에 (1/2) 를 곱해준다.
#     elif 4.95 < r < room_diagonal:     # 초과 면적이 2개 생긴다.
#         return (S - T) + ((1/2) * np.square(r) * np.arccos( 4.95 / r ) - (1/2) * np.pi * np.square(r) * np.sin(np.arccos( 4.95 / r )))
#     elif  r >= room_diagonal: # 반지름의 길이가 대각선의 길이보다 큰 경우, 초과면적은 부채꼴의 넓이 - 방넓이
#         return (np.square(r) * np.pi *(1/4)) - room_size
#     elif r < d :
#         return 0

def excess_area(R, d): # 초과면적 구하기
    if R > d: # 반지름의 길이가 방길이를 초과하는 경우 초과면적이 발생함
        return ((pow(R, 2) * math.acos(d / R)) - ((math.sqrt(pow(R, 2) - pow(d, 2)) * d))) / 2
    elif  R >= np.sqrt(np.square(3.15)+np.square(4.95)): # 반지름의 길이가 대각선의 길이보다 큰 경우 초과면적은 부채꼴의 넓이 - 방넓이
        return ((R**2) * 3.14 / 4) - 3.15 * 4.95 
    else:
        return 0   

In [48]:

for i in range(len(injury45)):  #len(injury45)
    # 레이더의 거리
    d_1 = distance_numpy_array[i][0]
    d_2 = distance_numpy_array[i][1]
    d_3 = distance_numpy_array[i][2]
    d_4 = distance_numpy_array[i][3]
    
    #방 면적
    room_size = 3.15 * 4.95 
    print(f'room size: {room_size}')
    print()
    # 부채꼴의 넓이의 합
    # print(f'부채꼴 넓이의 합 : {circular_sector_area(i).sum()}')
    print()
    # 교차면적 
    intersection_area_1_2 = intersection_area(d_1,d_2,4.95)  # 3.15는 가로 길이, 4.95는 세로 길이
    intersection_area_2_4 = intersection_area(d_2,d_4,3.15)
    intersection_area_4_3 = intersection_area(d_4,d_3,4.95)
    intersection_area_3_1 = intersection_area(d_3,d_1,3.15)
    total_intersection_area = intersection_area_1_2 +intersection_area_2_4 +intersection_area_4_3 +intersection_area_3_1
    print(f'total_intersection_area{total_intersection_area}')
    # 초과면적
    excess_area_1 = excess_area(d_1,3.15)
    excess_area_2 = excess_area(d_2,3.15)
    excess_area_3 = excess_area(d_3,3.15)
    excess_area_4 = excess_area(d_4,3.15)
    total_excess_area = excess_area_1 + excess_area_2 + excess_area_3 + excess_area_4
    print(f'total_excess_area{total_excess_area}')
    print()
    print(f'final area{room_size - circular_sector_area(i).sum() + total_intersection_area + total_excess_area}')
    print('----------------------------------------')

room size: 15.5925


total_intersection_area6.098627189272571
total_excess_area0.8746049966131024

final area0.6108684247114424
----------------------------------------
room size: 15.5925


total_intersection_area6.127510545862311
total_excess_area0.9013957824924983

final area0.5941101797470054
----------------------------------------
room size: 15.5925


total_intersection_area8.333371161123761
total_excess_area0.9409235108329725

final area0.5723653338905206
----------------------------------------
room size: 15.5925


total_intersection_area8.351538161689778
total_excess_area0.9650872643725892

final area0.5615215378653913
----------------------------------------
room size: 15.5925


total_intersection_area8.426513406076472
total_excess_area0.9932313785800888

final area0.5501462197879379
----------------------------------------
room size: 15.5925


total_intersection_area8.4695413914026
total_excess_area1.022165990804086

final area0.5355617410587792
------------------------------

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: divide by zero encountered in double_scalars
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  from ipykernel import kernelapp as app


TypeError: ignored

In [ ]:
def excess_area(R, d): # 초과면적 구하기
    if R > d: # 반지름의 길이가 방길이를 초과하는 경우 초과면적이 발생함
        return ((pow(R, 2) * math.acos(d / R)) - ((math.sqrt(pow(R, 2) - pow(d, 2)) * d))) / 2
    elif  R >= np.sqrt(np.square(3.15)+np.square(4.95)): # 반지름의 길이가 대각선의 길이보다 큰 경우 초과면적은 부채꼴의 넓이 - 방넓이
        return ((R**2) * 3.14 / 4) - 3.15 * 4.95 
    else:
        return 0

array([10.30639231,  9.41987255,  0.        ,  2.2285989 ])

In [ ]:
 print(circular_sector_area(0).sum())

21.95486376117423


In [ ]:
def intersection_area(R, r, d): # 부채꼴의 내각을 이용해서 교차면적 구하기 지희꺼
    t1 = theta(R, r, d)
    t2 = theta(r, R, d)
    if (R +r) < d:
        return 0
    elif (R == 0 or r == 0) and R + r > d:
        return 0
    elif (0 < R < d and 0 < r < d) and R + r > d:
        return ((pow(R, 2) * (t1 - math.sin(t1)) + pow(r, 2) * (t2 - math.sin(t2))) / 2) / 2
    elif (0 < R < d) and r > d:
        if R <= math.sqrt(pow(r, 2) - pow(d, 2)):
            return (R**2) * 3.14 / 4
        else:
            return ((((pow(R, 2) * (t1 - math.sin(t1)) + pow(r, 2) * (t2 - math.sin(t2))) / 2) / 2) - excess_area(r, d, diagonal_l, room_a))
    elif (0 < r < d) and R > d:
        if r <= math.sqrt(pow(R, 2) - pow(d, 2)):
            return (r**2) * 3.14 / 4
        else:
            return ((((pow(R, 2) * (t1 - math.sin(t1)) + pow(r, 2) * (t2 - math.sin(t2))) / 2) / 2) - excess_area(R, d, diagonal_l, room_a))
    else:
        return (pow(R, 2) * (t1 - math.sin(t1)) + pow(r, 2) * (t2 - math.sin(t2))) / 2